# Generated by Django 4.2.23 on 2025-08-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirmal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='desc',
            field=models.TextField(default='No description available'),
        ),
    ]
